Mobile-menu Project
AJ193/Portfolio-A pull request #10
Opened 2023-04-11 22:23 UTC by AJ193

The following new Features are implemented here:
-I use a JavaScript array to store all of the information for all projects
-All the projected where stored in array of objects.
-I updated the main page so that the projects section is created dynamically using the information stored in that JavaScript object.

2023-04-11 22:43 UTC, Munsa1 requested changes
Hi @AJ193, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have anything in the `future features` section. You can add the things you will do in future milestones as features such as, `modal popup`, desktop version` e.t.c.
![image](https://user-images.githubusercontent.com/81932478/231304579-87d51838-dcf9-4cc4-bcee-7639b83faed5.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-11 23:00 UTC, youmari requested changes
Hi @AJ193 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Great commit messages
✔️ PRO PR
✔️ No linter error 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-11 23:00 UTC, youmari commented on index.html
> +
- [ ] It would be better to use the same spacing, margin, padding, font-family font-size also please make sure to make the lines below the links as in the Figma design by using the same color 
- Yours 
<img width="400" alt="Screenshot 2023-04-11 at 22 55 11" src="https://user-images.githubusercontent.com/61790587/231306328-5c30d253-2357-4845-ab0f-f1239a9272eb.png">
- Design 
<img width="423" alt="Screenshot 2023-04-11 at 22 55 52" src="https://user-images.githubusercontent.com/61790587/231306357-74d2e332-cf92-44d4-b8b3-4e3982192dde.png">
<img width="174" alt="Screenshot 2023-04-11 at 23 00 09" src="https://user-images.githubusercontent.com/61790587/231306696-a7f9c561-8a44-4fa1-baa8-40c45132b5ce.png">

2023-04-11 23:00 UTC, youmari commented on app.js
> +}));
- [x] When I click on one of the links should take me to the right section right now it doesn't work as expected so please make sure to fix it

2023-04-12 07:39 UTC, emmiiorji approved these changes
Hi @AJ193 and Team, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<div align='center'>
<img src='https://user-images.githubusercontent.com/20554583/231016765-771515e9-2081-4dbc-aa48-cda4b05af5ff.gif'/>
</div>


## Good Highlights✔️

- Requested changes have been implemented

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-12 07:41 UTC, merged